<a href="https://colab.research.google.com/github/DanielVelezSolorzano/ArticuloCientifico_Latex_Computacion-en-la-nube./blob/main/Practica2_05_11_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#
#matrixA=np.ramdon
import numpy as np
matrixA=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(matrixA.shape)


(3, 4)


In [4]:
matrixA

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [5]:
print(matrixA[1:,1:3])

[[22 23]
 [32 33]]


In [8]:
# Crea una matriz 4x3 con números aleatorios entre 0 y 9
matriz = np.random.randint(0, 10, size=(4, 3))

# Imprime la matriz
print(matriz)

[[3 7 1]
 [5 8 9]
 [7 4 3]
 [7 0 8]]


In [9]:
print(matriz.shape)

(4, 3)


In [14]:
print(matriz)
col_indices=np.array([0,1,2])
row_indices=np.array([0,1,2])

for row, col in zip(row_indices,col_indices):
    print(matriz[row,col])
#print(row,"_",col)
#print(matriz[row_indices,col_indices])
#print(row_indices)
#print(col_indices)

[[3 7 1]
 [5 8 9]
 [7 4 3]
 [7 0 8]]
3
8
3


In [22]:
mask=matriz>7
print(mask)

[[False False False]
 [False  True  True]
 [False False False]
 [False False  True]]


In [23]:
print(matriz[mask])

[8 9 8]


In [24]:
print(matriz[matriz>7])

[8 9 8]


In [30]:
print(matriz)

[[306 308   9]
 [306   9 306]
 [  1 304 302]
 [  7 308   9]]


In [31]:
# Agrega 100 a los números pares
matriz[matriz % 2 == 0] += 100
print(matriz)

[[406 408   9]
 [406   9 406]
 [  1 404 402]
 [  7 408   9]]


In [32]:
# Crea una matriz 4x3 con números aleatorios entre 0 y 9
matriz = np.random.randint(0, 10, size=(4, 3))

# Agrega 100 a los números pares
matriz[matriz % 2 == 0] += 100

# Imprime la matriz modificada
print(matriz)

[[108 106 100]
 [  7 104 102]
 [102 104 100]
 [102 102   7]]


In [33]:
matriz[matriz % 2 == 0]+=100
print(matriz)

[[208 206 200]
 [  7 204 202]
 [202 204 200]
 [202 202   7]]


In [34]:
print(matriz)

[[208 206 200]
 [  7 204 202]
 [202 204 200]
 [202 202   7]]


In [39]:
9
mask = (matriz >= 3) & (matriz <= 9)
matriz[mask] += 100
print(matriz)

[[107 103   1]
 [109 208 100]
 [103 109   2]
 [107 106 204]]


In [41]:
matriz[(matriz > 3) & (matriz < 9)] += 100
print(matriz)

[[107 103   1]
 [109 208 100]
 [103 109   2]
 [107 106 204]]


In [42]:
matriz = np.random.choice([1, 2], size=(3, 3))

print(matriz)

[[1 1 2]
 [1 1 2]
 [1 2 2]]


In [45]:
matriz = np.random.choice([1, 2], size=(3, 3))

# Crea matriz1 (elementos 1) y matriz2 (elementos 2)
matriz1 = np.where(matriz == 1, matriz, 0)  # Donde matriz es 1, se mantiene, sino 0
matriz2 = np.where(matriz == 2, matriz, 0)  # Donde matriz es 2, se mantiene, sino 0

# Imprime las matrices
print("Matriz original:")
print(matriz)
print("\nMatriz1 (elementos 1):")
print(matriz1)
print("\nMatriz2 (elementos 2):")
print(matriz2)

Matriz original:
[[2 1 2]
 [1 1 1]
 [2 1 1]]

Matriz1 (elementos 1):
[[0 1 0]
 [1 1 1]
 [0 1 1]]

Matriz2 (elementos 2):
[[2 0 2]
 [0 0 0]
 [2 0 0]]


In [48]:
print(matriz1.sum())

6


In [46]:
print(matriz1.max())

1


In [49]:
start=np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [52]:
add_rows=np.array([1,2,3])
print(add_rows.shape)

(3,)


In [53]:
y=start+add_rows
print(y)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [54]:
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [56]:
col_rows=np.array([[1,2,3,4]])
col_rows=col_rows.T
print(col_rows)

[[1]
 [2]
 [3]
 [4]]


In [58]:
print(col_rows.shape)
tmp=col_rows.T
print(tmp.shape)

(4, 1)
(1, 4)


In [62]:
matriz = np.arange(1, 6).reshape(-1, 1)
matriz =np.repeat(matriz,1,axis=0)
print(matriz)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [63]:
print(start)
tmp=col_rows.T
print(tmp)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 2 3 4]]


In [67]:
tmp1 = np.array([[1, 1], [2, 2]])
tmp2 = np.array([[3, 3], [4, 4]])

print(tmp1)
print(tmp2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [69]:
matriz1 = np.random.randint(low=2, high=50, size=(2, 2))
matriz2 = np.random.randint(low=2, high=50, size=(2, 2))

print(matriz1)
print(matriz2)

[[ 6 41]
 [18  7]]
[[45 40]
 [29 17]]


In [70]:
np.vstack((matriz1,matriz2))

array([[ 6, 41],
       [18,  7],
       [45, 40],
       [29, 17]])

In [71]:
np.hstack((matriz1,matriz2))

array([[ 6, 41, 45, 40],
       [18,  7, 29, 17]])